env:
  global:
    CC_TEST_REPORTER_ID=ecb438ea2bc050c60e77fd231eaf2e6f675b7cb6aa64e87e2334a160ffc0bbb3
language: ruby
rvm:
 - 2.3.8
 - 2.5.1
 - 2.6.2
before_install:
- gem update --system
- gem install bundler
notifications:
- false
bundler_args: --without production
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rake
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT